# created by MecRoKa GBi 7.4.2022
 Edited by: Ameen Abdelaziz
#
# in this configuration file the types and our own names and parameters are defined for later use

/**:
  ros__parameters:
    use_sim_time: true
    
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    # the type joint state 'controller' is always needed to publish the joint states 
    # naming 'controller' is missleading - it just publishes the states!
    # so we rename it to 'broadcaster'
    my_joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
   
    my_diffdrive_controller:
      type: diff_drive_controller/DiffDriveController 
      
    my_ackrov_controller:
      type: ack_rov_controller/AckRovController       
      

             
# here we set the parameters for our controller(s) defined above
my_ackrov_controller:
  ros__parameters:
              
    left_wheel_names: ['steering_to_wheel_left_front','steering_to_wheel_left_middle','steering_to_wheel_left_rear']
    right_wheel_names: ['steering_to_wheel_right_front','steering_to_wheel_right_middle','steering_to_wheel_right_rear']
    left_steering_names: ['base_to_steering_left_front','base_to_steering_left_rear']                  
    right_steering_names: ['base_to_steering_right_front','base_to_steering_right_rear']               
    write_op_modes: ["motor_controller"]

    wheel_separation: 0.24
    wheels_per_side: 3  
    wheel_radius: 0.06
    wheel_base: 1.5
   


    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0
    
    

    publish_rate: 1000. 
    odom_frame_id: odom
    base_frame_id: base_footprint
    pose_covariance_diagonal: [0.00001, 0.00001, 1000000000000.0, 1000000000000.0, 1000000000000.0, 0.001]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]

    open_loop: false
    enable_odom_tf: true

    cmd_vel_timeout: 1.0 
    use_stamped_vel: false
    
    preserve_turning_radius: true
    
    publish_cmd: false
    
    publish_wheel_data: true

    linear.x.has_velocity_limits: true
    linear.x.has_acceleration_limits: true
    linear.x.has_jerk_limits: false
    linear.x.max_velocity: 0.7
    linear.x.min_velocity: -0.7
    linear.x.max_acceleration: 1.0
    linear.x.max_jerk: 0.0
    linear.x.min_jerk: 0.0
  
    angular.z.has_velocity_limits: true
    angular.z.has_acceleration_limits: true
    angular.z.has_jerk_limits: false
    angular.z.max_velocity: 2.0
    angular.z.min_velocity: -2.0
    angular.z.max_acceleration: 2.0
    angular.z.min_acceleration: -2.0
    angular.z.max_jerk: 0.0
    angular.z.min_jerk: 0.0                              
              
my_diffdrive_controller:
  ros__parameters:
              
    left_wheel_names: ['steering_to_wheel_left_front','steering_to_wheel_left_middle','steering_to_wheel_left_rear']
    right_wheel_names: ['steering_to_wheel_right_front','steering_to_wheel_right_middle','steering_to_wheel_right_rear']
    write_op_modes: ["motor_controller"]

    wheel_separation: 0.24
    wheels_per_side: 3  
    wheel_radius: 0.06

    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0
    

    publish_rate: 1000. 
    odom_frame_id: odom
    base_frame_id: base_footprint
    pose_covariance_diagonal: [0.00001, 0.00001, 1000000000000.0, 1000000000000.0, 1000000000000.0, 0.001]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]

    open_loop: false
    enable_odom_tf: true

    cmd_vel_timeout: 1.0 
    use_stamped_vel: false
    
    preserve_turning_radius: true
    
    publish_cmd: false
    
    publish_wheel_data: true

    linear.x.has_velocity_limits: true
    linear.x.has_acceleration_limits: true
    linear.x.has_jerk_limits: false
    linear.x.max_velocity: 0.7
    linear.x.min_velocity: -0.7
    linear.x.max_acceleration: 1.0
    linear.x.max_jerk: 0.0
    linear.x.min_jerk: 0.0
  
    angular.z.has_velocity_limits: true
    angular.z.has_acceleration_limits: true
    angular.z.has_jerk_limits: false
    angular.z.max_velocity: 2.0
    angular.z.min_velocity: -2.0
    angular.z.max_acceleration: 2.0
    angular.z.min_acceleration: -2.0
    angular.z.max_jerk: 0.0
    angular.z.min_jerk: 0.0      
    

